
namespace WindowsFormsApp4
{
    partial class MohtavaAmozeshiForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MohtavaAmozeshiForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel2 = new System.Windows.Forms.Panel();
            this.bunifuImageButton2 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.Mohtava = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.NarmNiyaz = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.About = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.MoarefiKetab = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.MorefiNarmAfzar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.pictureBox3 = new System.Windows.Forms.PictureBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.panel2.SuspendLayout();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.DarkRed;
            this.panel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.panel2.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.panel2.Controls.Add(this.bunifuImageButton2);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Right;
            this.panel2.Location = new System.Drawing.Point(815, 0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(171, 690);
            this.panel2.TabIndex = 27;
            this.panel2.Paint += new System.Windows.Forms.PaintEventHandler(this.panel2_Paint);
            // 
            // bunifuImageButton2
            // 
            this.bunifuImageButton2.ActiveImage = null;
            this.bunifuImageButton2.AllowAnimations = true;
            this.bunifuImageButton2.AllowBuffering = false;
            this.bunifuImageButton2.AllowToggling = false;
            this.bunifuImageButton2.AllowZooming = true;
            this.bunifuImageButton2.AllowZoomingOnFocus = false;
            this.bunifuImageButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton2.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.ErrorImage")));
            this.bunifuImageButton2.FadeWhenInactive = false;
            this.bunifuImageButton2.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.Image")));
            this.bunifuImageButton2.ImageActive = null;
            this.bunifuImageButton2.ImageLocation = null;
            this.bunifuImageButton2.ImageMargin = 0;
            this.bunifuImageButton2.ImageSize = new System.Drawing.Size(165, 543);
            this.bunifuImageButton2.ImageZoomSize = new System.Drawing.Size(166, 544);
            this.bunifuImageButton2.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.InitialImage")));
            this.bunifuImageButton2.Location = new System.Drawing.Point(3, 43);
            this.bunifuImageButton2.Margin = new System.Windows.Forms.Padding(3, 5, 3, 5);
            this.bunifuImageButton2.Name = "bunifuImageButton2";
            this.bunifuImageButton2.Rotation = 0;
            this.bunifuImageButton2.ShowActiveImage = true;
            this.bunifuImageButton2.ShowCursorChanges = true;
            this.bunifuImageButton2.ShowImageBorders = true;
            this.bunifuImageButton2.ShowSizeMarkers = false;
            this.bunifuImageButton2.Size = new System.Drawing.Size(166, 544);
            this.bunifuImageButton2.TabIndex = 0;
            this.bunifuImageButton2.ToolTipText = "";
            this.bunifuImageButton2.WaitOnLoad = false;
            this.bunifuImageButton2.Zoom = 0;
            this.bunifuImageButton2.ZoomSpeed = 10;
            this.bunifuImageButton2.Click += new System.EventHandler(this.bunifuImageButton2_Click);
            // 
            // Mohtava
            // 
            this.Mohtava.AllowAnimations = true;
            this.Mohtava.AllowMouseEffects = true;
            this.Mohtava.AllowToggling = true;
            this.Mohtava.AnimationSpeed = 200;
            this.Mohtava.AutoGenerateColors = false;
            this.Mohtava.AutoRoundBorders = false;
            this.Mohtava.AutoSizeLeftIcon = true;
            this.Mohtava.AutoSizeRightIcon = true;
            this.Mohtava.BackColor = System.Drawing.Color.Transparent;
            this.Mohtava.BackColor1 = System.Drawing.Color.GhostWhite;
            this.Mohtava.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Mohtava.BackgroundImage")));
            this.Mohtava.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.Mohtava.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Mohtava.ButtonText = "آشنایی با ابزار و وسایل دندانپزشکی";
            this.Mohtava.ButtonTextMarginLeft = 0;
            this.Mohtava.CausesValidation = false;
            this.Mohtava.ColorContrastOnClick = 500;
            this.Mohtava.ColorContrastOnHover = 0;
            this.Mohtava.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.Mohtava.CustomizableEdges = borderEdges1;
            this.Mohtava.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Mohtava.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Mohtava.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Mohtava.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.Mohtava.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.Mohtava.Font = new System.Drawing.Font("2  Baran", 20F);
            this.Mohtava.ForeColor = System.Drawing.Color.Black;
            this.Mohtava.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Mohtava.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Mohtava.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Mohtava.IconMarginLeft = 11;
            this.Mohtava.IconPadding = 10;
            this.Mohtava.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Mohtava.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Mohtava.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Mohtava.IconSize = 25;
            this.Mohtava.IdleBorderColor = System.Drawing.Color.Maroon;
            this.Mohtava.IdleBorderRadius = 40;
            this.Mohtava.IdleBorderThickness = 2;
            this.Mohtava.IdleFillColor = System.Drawing.Color.GhostWhite;
            this.Mohtava.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("Mohtava.IdleIconLeftImage")));
            this.Mohtava.IdleIconRightImage = null;
            this.Mohtava.ImeMode = System.Windows.Forms.ImeMode.AlphaFull;
            this.Mohtava.IndicateFocus = true;
            this.Mohtava.Location = new System.Drawing.Point(190, 36);
            this.Mohtava.Name = "Mohtava";
            this.Mohtava.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Mohtava.OnDisabledState.BorderRadius = 40;
            this.Mohtava.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Mohtava.OnDisabledState.BorderThickness = 2;
            this.Mohtava.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Mohtava.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.Mohtava.OnDisabledState.IconLeftImage = null;
            this.Mohtava.OnDisabledState.IconRightImage = null;
            this.Mohtava.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Mohtava.onHoverState.BorderRadius = 40;
            this.Mohtava.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Mohtava.onHoverState.BorderThickness = 2;
            this.Mohtava.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Mohtava.onHoverState.ForeColor = System.Drawing.Color.Maroon;
            this.Mohtava.onHoverState.IconLeftImage = null;
            this.Mohtava.onHoverState.IconRightImage = null;
            this.Mohtava.OnIdleState.BorderColor = System.Drawing.Color.Maroon;
            this.Mohtava.OnIdleState.BorderRadius = 40;
            this.Mohtava.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Mohtava.OnIdleState.BorderThickness = 2;
            this.Mohtava.OnIdleState.FillColor = System.Drawing.Color.GhostWhite;
            this.Mohtava.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Mohtava.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("Mohtava.OnIdleState.IconLeftImage")));
            this.Mohtava.OnIdleState.IconRightImage = null;
            this.Mohtava.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Mohtava.OnPressedState.BorderRadius = 40;
            this.Mohtava.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Mohtava.OnPressedState.BorderThickness = 2;
            this.Mohtava.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Mohtava.OnPressedState.ForeColor = System.Drawing.Color.Maroon;
            this.Mohtava.OnPressedState.IconLeftImage = null;
            this.Mohtava.OnPressedState.IconRightImage = null;
            this.Mohtava.Size = new System.Drawing.Size(610, 61);
            this.Mohtava.TabIndex = 28;
            this.Mohtava.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Mohtava.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Mohtava.TextMarginLeft = 0;
            this.Mohtava.TextPadding = new System.Windows.Forms.Padding(0);
            this.Mohtava.UseDefaultRadiusAndThickness = true;
            this.Mohtava.Click += new System.EventHandler(this.Mohtava_Click);
            // 
            // NarmNiyaz
            // 
            this.NarmNiyaz.AllowAnimations = true;
            this.NarmNiyaz.AllowMouseEffects = true;
            this.NarmNiyaz.AllowToggling = false;
            this.NarmNiyaz.AnimationSpeed = 200;
            this.NarmNiyaz.AutoGenerateColors = false;
            this.NarmNiyaz.AutoRoundBorders = false;
            this.NarmNiyaz.AutoSizeLeftIcon = true;
            this.NarmNiyaz.AutoSizeRightIcon = true;
            this.NarmNiyaz.BackColor = System.Drawing.Color.Transparent;
            this.NarmNiyaz.BackColor1 = System.Drawing.Color.LavenderBlush;
            this.NarmNiyaz.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NarmNiyaz.BackgroundImage")));
            this.NarmNiyaz.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NarmNiyaz.ButtonText = "نرم افزارهای مورد نیاز";
            this.NarmNiyaz.ButtonTextMarginLeft = 0;
            this.NarmNiyaz.ColorContrastOnClick = 45;
            this.NarmNiyaz.ColorContrastOnHover = 45;
            this.NarmNiyaz.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.NarmNiyaz.CustomizableEdges = borderEdges2;
            this.NarmNiyaz.DialogResult = System.Windows.Forms.DialogResult.None;
            this.NarmNiyaz.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.NarmNiyaz.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NarmNiyaz.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.NarmNiyaz.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.NarmNiyaz.Font = new System.Drawing.Font("2  Baran", 10F);
            this.NarmNiyaz.ForeColor = System.Drawing.Color.Black;
            this.NarmNiyaz.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.NarmNiyaz.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.NarmNiyaz.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.NarmNiyaz.IconMarginLeft = 11;
            this.NarmNiyaz.IconPadding = 10;
            this.NarmNiyaz.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.NarmNiyaz.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.NarmNiyaz.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.NarmNiyaz.IconSize = 25;
            this.NarmNiyaz.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(13)))), ((int)(((byte)(49)))));
            this.NarmNiyaz.IdleBorderRadius = 40;
            this.NarmNiyaz.IdleBorderThickness = 1;
            this.NarmNiyaz.IdleFillColor = System.Drawing.Color.LavenderBlush;
            this.NarmNiyaz.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("NarmNiyaz.IdleIconLeftImage")));
            this.NarmNiyaz.IdleIconRightImage = null;
            this.NarmNiyaz.IndicateFocus = false;
            this.NarmNiyaz.Location = new System.Drawing.Point(3, 584);
            this.NarmNiyaz.Name = "NarmNiyaz";
            this.NarmNiyaz.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.NarmNiyaz.OnDisabledState.BorderRadius = 40;
            this.NarmNiyaz.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NarmNiyaz.OnDisabledState.BorderThickness = 1;
            this.NarmNiyaz.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NarmNiyaz.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.NarmNiyaz.OnDisabledState.IconLeftImage = null;
            this.NarmNiyaz.OnDisabledState.IconRightImage = null;
            this.NarmNiyaz.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NarmNiyaz.onHoverState.BorderRadius = 40;
            this.NarmNiyaz.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NarmNiyaz.onHoverState.BorderThickness = 1;
            this.NarmNiyaz.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NarmNiyaz.onHoverState.ForeColor = System.Drawing.Color.White;
            this.NarmNiyaz.onHoverState.IconLeftImage = null;
            this.NarmNiyaz.onHoverState.IconRightImage = null;
            this.NarmNiyaz.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(13)))), ((int)(((byte)(49)))));
            this.NarmNiyaz.OnIdleState.BorderRadius = 40;
            this.NarmNiyaz.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NarmNiyaz.OnIdleState.BorderThickness = 1;
            this.NarmNiyaz.OnIdleState.FillColor = System.Drawing.Color.LavenderBlush;
            this.NarmNiyaz.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.NarmNiyaz.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("NarmNiyaz.OnIdleState.IconLeftImage")));
            this.NarmNiyaz.OnIdleState.IconRightImage = null;
            this.NarmNiyaz.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.NarmNiyaz.OnPressedState.BorderRadius = 40;
            this.NarmNiyaz.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NarmNiyaz.OnPressedState.BorderThickness = 1;
            this.NarmNiyaz.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.NarmNiyaz.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.NarmNiyaz.OnPressedState.IconLeftImage = null;
            this.NarmNiyaz.OnPressedState.IconRightImage = null;
            this.NarmNiyaz.Size = new System.Drawing.Size(170, 75);
            this.NarmNiyaz.TabIndex = 5;
            this.NarmNiyaz.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.NarmNiyaz.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.NarmNiyaz.TextMarginLeft = 0;
            this.NarmNiyaz.TextPadding = new System.Windows.Forms.Padding(0);
            this.NarmNiyaz.UseDefaultRadiusAndThickness = true;
            this.NarmNiyaz.Click += new System.EventHandler(this.NarmNiyaz_Click);
            // 
            // About
            // 
            this.About.AllowAnimations = true;
            this.About.AllowMouseEffects = true;
            this.About.AllowToggling = false;
            this.About.AnimationSpeed = 200;
            this.About.AutoGenerateColors = false;
            this.About.AutoRoundBorders = false;
            this.About.AutoSizeLeftIcon = true;
            this.About.AutoSizeRightIcon = true;
            this.About.BackColor = System.Drawing.Color.Transparent;
            this.About.BackColor1 = System.Drawing.Color.LavenderBlush;
            this.About.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("About.BackgroundImage")));
            this.About.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.About.ButtonText = "درباره پدیدآورندگان";
            this.About.ButtonTextMarginLeft = 0;
            this.About.ColorContrastOnClick = 45;
            this.About.ColorContrastOnHover = 45;
            this.About.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.About.CustomizableEdges = borderEdges3;
            this.About.DialogResult = System.Windows.Forms.DialogResult.None;
            this.About.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.About.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.About.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.About.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.About.Font = new System.Drawing.Font("2  Baran", 10F);
            this.About.ForeColor = System.Drawing.Color.Black;
            this.About.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.About.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.About.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.About.IconMarginLeft = 11;
            this.About.IconPadding = 10;
            this.About.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.About.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.About.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.About.IconSize = 25;
            this.About.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(13)))), ((int)(((byte)(49)))));
            this.About.IdleBorderRadius = 40;
            this.About.IdleBorderThickness = 1;
            this.About.IdleFillColor = System.Drawing.Color.LavenderBlush;
            this.About.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("About.IdleIconLeftImage")));
            this.About.IdleIconRightImage = null;
            this.About.IndicateFocus = false;
            this.About.Location = new System.Drawing.Point(3, 505);
            this.About.Name = "About";
            this.About.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.About.OnDisabledState.BorderRadius = 40;
            this.About.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.About.OnDisabledState.BorderThickness = 1;
            this.About.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.About.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.About.OnDisabledState.IconLeftImage = null;
            this.About.OnDisabledState.IconRightImage = null;
            this.About.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.About.onHoverState.BorderRadius = 40;
            this.About.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.About.onHoverState.BorderThickness = 1;
            this.About.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.About.onHoverState.ForeColor = System.Drawing.Color.White;
            this.About.onHoverState.IconLeftImage = null;
            this.About.onHoverState.IconRightImage = null;
            this.About.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(13)))), ((int)(((byte)(49)))));
            this.About.OnIdleState.BorderRadius = 40;
            this.About.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.About.OnIdleState.BorderThickness = 1;
            this.About.OnIdleState.FillColor = System.Drawing.Color.LavenderBlush;
            this.About.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.About.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("About.OnIdleState.IconLeftImage")));
            this.About.OnIdleState.IconRightImage = null;
            this.About.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.About.OnPressedState.BorderRadius = 40;
            this.About.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.About.OnPressedState.BorderThickness = 1;
            this.About.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.About.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.About.OnPressedState.IconLeftImage = null;
            this.About.OnPressedState.IconRightImage = null;
            this.About.Size = new System.Drawing.Size(170, 73);
            this.About.TabIndex = 4;
            this.About.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.About.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.About.TextMarginLeft = 0;
            this.About.TextPadding = new System.Windows.Forms.Padding(0);
            this.About.UseDefaultRadiusAndThickness = true;
            this.About.Click += new System.EventHandler(this.About_Click);
            // 
            // MoarefiKetab
            // 
            this.MoarefiKetab.AllowAnimations = true;
            this.MoarefiKetab.AllowMouseEffects = true;
            this.MoarefiKetab.AllowToggling = false;
            this.MoarefiKetab.AnimationSpeed = 200;
            this.MoarefiKetab.AutoGenerateColors = false;
            this.MoarefiKetab.AutoRoundBorders = false;
            this.MoarefiKetab.AutoSizeLeftIcon = true;
            this.MoarefiKetab.AutoSizeRightIcon = true;
            this.MoarefiKetab.BackColor = System.Drawing.Color.Transparent;
            this.MoarefiKetab.BackColor1 = System.Drawing.Color.LavenderBlush;
            this.MoarefiKetab.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("MoarefiKetab.BackgroundImage")));
            this.MoarefiKetab.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MoarefiKetab.ButtonText = "معرفی کتاب";
            this.MoarefiKetab.ButtonTextMarginLeft = 0;
            this.MoarefiKetab.ColorContrastOnClick = 45;
            this.MoarefiKetab.ColorContrastOnHover = 45;
            this.MoarefiKetab.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.MoarefiKetab.CustomizableEdges = borderEdges4;
            this.MoarefiKetab.DialogResult = System.Windows.Forms.DialogResult.None;
            this.MoarefiKetab.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.MoarefiKetab.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.MoarefiKetab.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.MoarefiKetab.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.MoarefiKetab.Font = new System.Drawing.Font("2  Baran", 12F);
            this.MoarefiKetab.ForeColor = System.Drawing.Color.Black;
            this.MoarefiKetab.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.MoarefiKetab.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.MoarefiKetab.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.MoarefiKetab.IconMarginLeft = 11;
            this.MoarefiKetab.IconPadding = 10;
            this.MoarefiKetab.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.MoarefiKetab.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.MoarefiKetab.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.MoarefiKetab.IconSize = 25;
            this.MoarefiKetab.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(13)))), ((int)(((byte)(49)))));
            this.MoarefiKetab.IdleBorderRadius = 40;
            this.MoarefiKetab.IdleBorderThickness = 1;
            this.MoarefiKetab.IdleFillColor = System.Drawing.Color.LavenderBlush;
            this.MoarefiKetab.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("MoarefiKetab.IdleIconLeftImage")));
            this.MoarefiKetab.IdleIconRightImage = null;
            this.MoarefiKetab.IndicateFocus = false;
            this.MoarefiKetab.Location = new System.Drawing.Point(3, 428);
            this.MoarefiKetab.Name = "MoarefiKetab";
            this.MoarefiKetab.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.MoarefiKetab.OnDisabledState.BorderRadius = 40;
            this.MoarefiKetab.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MoarefiKetab.OnDisabledState.BorderThickness = 1;
            this.MoarefiKetab.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.MoarefiKetab.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.MoarefiKetab.OnDisabledState.IconLeftImage = null;
            this.MoarefiKetab.OnDisabledState.IconRightImage = null;
            this.MoarefiKetab.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.MoarefiKetab.onHoverState.BorderRadius = 40;
            this.MoarefiKetab.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MoarefiKetab.onHoverState.BorderThickness = 1;
            this.MoarefiKetab.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.MoarefiKetab.onHoverState.ForeColor = System.Drawing.Color.White;
            this.MoarefiKetab.onHoverState.IconLeftImage = null;
            this.MoarefiKetab.onHoverState.IconRightImage = null;
            this.MoarefiKetab.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(13)))), ((int)(((byte)(49)))));
            this.MoarefiKetab.OnIdleState.BorderRadius = 40;
            this.MoarefiKetab.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MoarefiKetab.OnIdleState.BorderThickness = 1;
            this.MoarefiKetab.OnIdleState.FillColor = System.Drawing.Color.LavenderBlush;
            this.MoarefiKetab.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.MoarefiKetab.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("MoarefiKetab.OnIdleState.IconLeftImage")));
            this.MoarefiKetab.OnIdleState.IconRightImage = null;
            this.MoarefiKetab.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.MoarefiKetab.OnPressedState.BorderRadius = 40;
            this.MoarefiKetab.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MoarefiKetab.OnPressedState.BorderThickness = 1;
            this.MoarefiKetab.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.MoarefiKetab.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.MoarefiKetab.OnPressedState.IconLeftImage = null;
            this.MoarefiKetab.OnPressedState.IconRightImage = null;
            this.MoarefiKetab.Size = new System.Drawing.Size(170, 71);
            this.MoarefiKetab.TabIndex = 1;
            this.MoarefiKetab.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.MoarefiKetab.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.MoarefiKetab.TextMarginLeft = 0;
            this.MoarefiKetab.TextPadding = new System.Windows.Forms.Padding(0);
            this.MoarefiKetab.UseDefaultRadiusAndThickness = true;
            this.MoarefiKetab.Click += new System.EventHandler(this.MoarefiKetab_Click);
            // 
            // MorefiNarmAfzar
            // 
            this.MorefiNarmAfzar.AllowAnimations = true;
            this.MorefiNarmAfzar.AllowMouseEffects = true;
            this.MorefiNarmAfzar.AllowToggling = false;
            this.MorefiNarmAfzar.AnimationSpeed = 200;
            this.MorefiNarmAfzar.AutoGenerateColors = false;
            this.MorefiNarmAfzar.AutoRoundBorders = false;
            this.MorefiNarmAfzar.AutoSizeLeftIcon = true;
            this.MorefiNarmAfzar.AutoSizeRightIcon = true;
            this.MorefiNarmAfzar.BackColor = System.Drawing.Color.Transparent;
            this.MorefiNarmAfzar.BackColor1 = System.Drawing.Color.LavenderBlush;
            this.MorefiNarmAfzar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("MorefiNarmAfzar.BackgroundImage")));
            this.MorefiNarmAfzar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MorefiNarmAfzar.ButtonText = "معرفی نرم افزار";
            this.MorefiNarmAfzar.ButtonTextMarginLeft = 0;
            this.MorefiNarmAfzar.ColorContrastOnClick = 45;
            this.MorefiNarmAfzar.ColorContrastOnHover = 45;
            this.MorefiNarmAfzar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.MorefiNarmAfzar.CustomizableEdges = borderEdges5;
            this.MorefiNarmAfzar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.MorefiNarmAfzar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.MorefiNarmAfzar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.MorefiNarmAfzar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.MorefiNarmAfzar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.MorefiNarmAfzar.Font = new System.Drawing.Font("2  Baran", 12F);
            this.MorefiNarmAfzar.ForeColor = System.Drawing.Color.Black;
            this.MorefiNarmAfzar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.MorefiNarmAfzar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.MorefiNarmAfzar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.MorefiNarmAfzar.IconMarginLeft = 11;
            this.MorefiNarmAfzar.IconPadding = 10;
            this.MorefiNarmAfzar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.MorefiNarmAfzar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.MorefiNarmAfzar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.MorefiNarmAfzar.IconSize = 25;
            this.MorefiNarmAfzar.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(13)))), ((int)(((byte)(49)))));
            this.MorefiNarmAfzar.IdleBorderRadius = 40;
            this.MorefiNarmAfzar.IdleBorderThickness = 1;
            this.MorefiNarmAfzar.IdleFillColor = System.Drawing.Color.LavenderBlush;
            this.MorefiNarmAfzar.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("MorefiNarmAfzar.IdleIconLeftImage")));
            this.MorefiNarmAfzar.IdleIconRightImage = null;
            this.MorefiNarmAfzar.IndicateFocus = false;
            this.MorefiNarmAfzar.Location = new System.Drawing.Point(3, 349);
            this.MorefiNarmAfzar.Name = "MorefiNarmAfzar";
            this.MorefiNarmAfzar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.MorefiNarmAfzar.OnDisabledState.BorderRadius = 40;
            this.MorefiNarmAfzar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MorefiNarmAfzar.OnDisabledState.BorderThickness = 1;
            this.MorefiNarmAfzar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.MorefiNarmAfzar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.MorefiNarmAfzar.OnDisabledState.IconLeftImage = null;
            this.MorefiNarmAfzar.OnDisabledState.IconRightImage = null;
            this.MorefiNarmAfzar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.MorefiNarmAfzar.onHoverState.BorderRadius = 40;
            this.MorefiNarmAfzar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MorefiNarmAfzar.onHoverState.BorderThickness = 1;
            this.MorefiNarmAfzar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.MorefiNarmAfzar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.MorefiNarmAfzar.onHoverState.IconLeftImage = null;
            this.MorefiNarmAfzar.onHoverState.IconRightImage = null;
            this.MorefiNarmAfzar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(13)))), ((int)(((byte)(49)))));
            this.MorefiNarmAfzar.OnIdleState.BorderRadius = 40;
            this.MorefiNarmAfzar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MorefiNarmAfzar.OnIdleState.BorderThickness = 1;
            this.MorefiNarmAfzar.OnIdleState.FillColor = System.Drawing.Color.LavenderBlush;
            this.MorefiNarmAfzar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.MorefiNarmAfzar.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("MorefiNarmAfzar.OnIdleState.IconLeftImage")));
            this.MorefiNarmAfzar.OnIdleState.IconRightImage = null;
            this.MorefiNarmAfzar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.MorefiNarmAfzar.OnPressedState.BorderRadius = 40;
            this.MorefiNarmAfzar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MorefiNarmAfzar.OnPressedState.BorderThickness = 1;
            this.MorefiNarmAfzar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.MorefiNarmAfzar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.MorefiNarmAfzar.OnPressedState.IconLeftImage = null;
            this.MorefiNarmAfzar.OnPressedState.IconRightImage = null;
            this.MorefiNarmAfzar.Size = new System.Drawing.Size(170, 73);
            this.MorefiNarmAfzar.TabIndex = 1;
            this.MorefiNarmAfzar.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.MorefiNarmAfzar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.MorefiNarmAfzar.TextMarginLeft = 0;
            this.MorefiNarmAfzar.TextPadding = new System.Windows.Forms.Padding(0);
            this.MorefiNarmAfzar.UseDefaultRadiusAndThickness = true;
            this.MorefiNarmAfzar.Click += new System.EventHandler(this.MorefiNarmAfzar_Click);
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.Firebrick;
            this.panel1.Controls.Add(this.pictureBox3);
            this.panel1.Controls.Add(this.pictureBox2);
            this.panel1.Controls.Add(this.NarmNiyaz);
            this.panel1.Controls.Add(this.About);
            this.panel1.Controls.Add(this.MoarefiKetab);
            this.panel1.Controls.Add(this.MorefiNarmAfzar);
            this.panel1.Controls.Add(this.pictureBox1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(182, 690);
            this.panel1.TabIndex = 26;
            this.panel1.Paint += new System.Windows.Forms.PaintEventHandler(this.panel1_Paint);
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = true;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.GhostWhite;
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "آشنایی با کلیات کامپوزیت";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.CausesValidation = false;
            this.bunifuButton2.ColorContrastOnClick = 500;
            this.bunifuButton2.ColorContrastOnHover = 0;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges6;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.bunifuButton2.Font = new System.Drawing.Font("2  Baran", 20F);
            this.bunifuButton2.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.Maroon;
            this.bunifuButton2.IdleBorderRadius = 40;
            this.bunifuButton2.IdleBorderThickness = 2;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.GhostWhite;
            this.bunifuButton2.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.IdleIconLeftImage")));
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.ImeMode = System.Windows.Forms.ImeMode.AlphaFull;
            this.bunifuButton2.IndicateFocus = true;
            this.bunifuButton2.Location = new System.Drawing.Point(188, 340);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 40;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 2;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 40;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 2;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.Maroon;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.Maroon;
            this.bunifuButton2.OnIdleState.BorderRadius = 40;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 2;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.GhostWhite;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton2.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.OnIdleState.IconLeftImage")));
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 40;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 2;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.Maroon;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(610, 61);
            this.bunifuButton2.TabIndex = 29;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowAnimations = true;
            this.bunifuButton3.AllowMouseEffects = true;
            this.bunifuButton3.AllowToggling = true;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.AutoRoundBorders = false;
            this.bunifuButton3.AutoSizeLeftIcon = true;
            this.bunifuButton3.AutoSizeRightIcon = true;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.GhostWhite;
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "آشنایی با تهیه حفره و ترمیم های کامپوزیت";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.CausesValidation = false;
            this.bunifuButton3.ColorContrastOnClick = 500;
            this.bunifuButton3.ColorContrastOnHover = 0;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges7;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.bunifuButton3.Font = new System.Drawing.Font("2  Baran", 20F);
            this.bunifuButton3.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton3.IconSize = 25;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.Maroon;
            this.bunifuButton3.IdleBorderRadius = 40;
            this.bunifuButton3.IdleBorderThickness = 2;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.GhostWhite;
            this.bunifuButton3.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.IdleIconLeftImage")));
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.ImeMode = System.Windows.Forms.ImeMode.AlphaFull;
            this.bunifuButton3.IndicateFocus = true;
            this.bunifuButton3.Location = new System.Drawing.Point(188, 418);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton3.OnDisabledState.BorderRadius = 40;
            this.bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnDisabledState.BorderThickness = 2;
            this.bunifuButton3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton3.OnDisabledState.IconLeftImage = null;
            this.bunifuButton3.OnDisabledState.IconRightImage = null;
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.BorderRadius = 40;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 2;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.Maroon;
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.Maroon;
            this.bunifuButton3.OnIdleState.BorderRadius = 40;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnIdleState.BorderThickness = 2;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.GhostWhite;
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton3.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.OnIdleState.IconLeftImage")));
            this.bunifuButton3.OnIdleState.IconRightImage = null;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.BorderRadius = 40;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 2;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.Maroon;
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(610, 61);
            this.bunifuButton3.TabIndex = 30;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            this.bunifuButton3.Click += new System.EventHandler(this.bunifuButton3_Click);
            // 
            // bunifuButton7
            // 
            this.bunifuButton7.AllowAnimations = true;
            this.bunifuButton7.AllowMouseEffects = true;
            this.bunifuButton7.AllowToggling = true;
            this.bunifuButton7.AnimationSpeed = 200;
            this.bunifuButton7.AutoGenerateColors = false;
            this.bunifuButton7.AutoRoundBorders = false;
            this.bunifuButton7.AutoSizeLeftIcon = true;
            this.bunifuButton7.AutoSizeRightIcon = true;
            this.bunifuButton7.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton7.BackColor1 = System.Drawing.Color.GhostWhite;
            this.bunifuButton7.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton7.BackgroundImage")));
            this.bunifuButton7.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.bunifuButton7.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton7.ButtonText = "آشنایی با تهیه حفره و ترمیم های آمالگام";
            this.bunifuButton7.ButtonTextMarginLeft = 0;
            this.bunifuButton7.CausesValidation = false;
            this.bunifuButton7.ColorContrastOnClick = 500;
            this.bunifuButton7.ColorContrastOnHover = 0;
            this.bunifuButton7.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bunifuButton7.CustomizableEdges = borderEdges8;
            this.bunifuButton7.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton7.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton7.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton7.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton7.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.bunifuButton7.Font = new System.Drawing.Font("2  Baran", 20F);
            this.bunifuButton7.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton7.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton7.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton7.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton7.IconMarginLeft = 11;
            this.bunifuButton7.IconPadding = 10;
            this.bunifuButton7.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton7.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton7.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton7.IconSize = 25;
            this.bunifuButton7.IdleBorderColor = System.Drawing.Color.Maroon;
            this.bunifuButton7.IdleBorderRadius = 40;
            this.bunifuButton7.IdleBorderThickness = 2;
            this.bunifuButton7.IdleFillColor = System.Drawing.Color.GhostWhite;
            this.bunifuButton7.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton7.IdleIconLeftImage")));
            this.bunifuButton7.IdleIconRightImage = null;
            this.bunifuButton7.ImeMode = System.Windows.Forms.ImeMode.AlphaFull;
            this.bunifuButton7.IndicateFocus = true;
            this.bunifuButton7.Location = new System.Drawing.Point(188, 264);
            this.bunifuButton7.Name = "bunifuButton7";
            this.bunifuButton7.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton7.OnDisabledState.BorderRadius = 40;
            this.bunifuButton7.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton7.OnDisabledState.BorderThickness = 2;
            this.bunifuButton7.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton7.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton7.OnDisabledState.IconLeftImage = null;
            this.bunifuButton7.OnDisabledState.IconRightImage = null;
            this.bunifuButton7.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton7.onHoverState.BorderRadius = 40;
            this.bunifuButton7.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton7.onHoverState.BorderThickness = 2;
            this.bunifuButton7.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton7.onHoverState.ForeColor = System.Drawing.Color.Maroon;
            this.bunifuButton7.onHoverState.IconLeftImage = null;
            this.bunifuButton7.onHoverState.IconRightImage = null;
            this.bunifuButton7.OnIdleState.BorderColor = System.Drawing.Color.Maroon;
            this.bunifuButton7.OnIdleState.BorderRadius = 40;
            this.bunifuButton7.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton7.OnIdleState.BorderThickness = 2;
            this.bunifuButton7.OnIdleState.FillColor = System.Drawing.Color.GhostWhite;
            this.bunifuButton7.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton7.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton7.OnIdleState.IconLeftImage")));
            this.bunifuButton7.OnIdleState.IconRightImage = null;
            this.bunifuButton7.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton7.OnPressedState.BorderRadius = 40;
            this.bunifuButton7.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton7.OnPressedState.BorderThickness = 2;
            this.bunifuButton7.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton7.OnPressedState.ForeColor = System.Drawing.Color.Maroon;
            this.bunifuButton7.OnPressedState.IconLeftImage = null;
            this.bunifuButton7.OnPressedState.IconRightImage = null;
            this.bunifuButton7.Size = new System.Drawing.Size(610, 61);
            this.bunifuButton7.TabIndex = 32;
            this.bunifuButton7.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton7.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton7.TextMarginLeft = 0;
            this.bunifuButton7.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton7.UseDefaultRadiusAndThickness = true;
            this.bunifuButton7.Click += new System.EventHandler(this.bunifuButton7_Click);
            // 
            // bunifuButton8
            // 
            this.bunifuButton8.AllowAnimations = true;
            this.bunifuButton8.AllowMouseEffects = true;
            this.bunifuButton8.AllowToggling = true;
            this.bunifuButton8.AnimationSpeed = 200;
            this.bunifuButton8.AutoGenerateColors = false;
            this.bunifuButton8.AutoRoundBorders = false;
            this.bunifuButton8.AutoSizeLeftIcon = true;
            this.bunifuButton8.AutoSizeRightIcon = true;
            this.bunifuButton8.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton8.BackColor1 = System.Drawing.Color.GhostWhite;
            this.bunifuButton8.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton8.BackgroundImage")));
            this.bunifuButton8.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.bunifuButton8.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton8.ButtonText = "آشنایی با کلیات مربوط به آمالگام و اصول آماده سازی اولیه";
            this.bunifuButton8.ButtonTextMarginLeft = 0;
            this.bunifuButton8.CausesValidation = false;
            this.bunifuButton8.ColorContrastOnClick = 500;
            this.bunifuButton8.ColorContrastOnHover = 0;
            this.bunifuButton8.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.bunifuButton8.CustomizableEdges = borderEdges9;
            this.bunifuButton8.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton8.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton8.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton8.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton8.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.bunifuButton8.Font = new System.Drawing.Font("2  Baran", 20F);
            this.bunifuButton8.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton8.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton8.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton8.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton8.IconMarginLeft = 11;
            this.bunifuButton8.IconPadding = 10;
            this.bunifuButton8.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton8.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton8.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton8.IconSize = 25;
            this.bunifuButton8.IdleBorderColor = System.Drawing.Color.Maroon;
            this.bunifuButton8.IdleBorderRadius = 40;
            this.bunifuButton8.IdleBorderThickness = 2;
            this.bunifuButton8.IdleFillColor = System.Drawing.Color.GhostWhite;
            this.bunifuButton8.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton8.IdleIconLeftImage")));
            this.bunifuButton8.IdleIconRightImage = null;
            this.bunifuButton8.ImeMode = System.Windows.Forms.ImeMode.AlphaFull;
            this.bunifuButton8.IndicateFocus = true;
            this.bunifuButton8.Location = new System.Drawing.Point(190, 188);
            this.bunifuButton8.Name = "bunifuButton8";
            this.bunifuButton8.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton8.OnDisabledState.BorderRadius = 40;
            this.bunifuButton8.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton8.OnDisabledState.BorderThickness = 2;
            this.bunifuButton8.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton8.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton8.OnDisabledState.IconLeftImage = null;
            this.bunifuButton8.OnDisabledState.IconRightImage = null;
            this.bunifuButton8.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton8.onHoverState.BorderRadius = 40;
            this.bunifuButton8.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton8.onHoverState.BorderThickness = 2;
            this.bunifuButton8.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton8.onHoverState.ForeColor = System.Drawing.Color.Maroon;
            this.bunifuButton8.onHoverState.IconLeftImage = null;
            this.bunifuButton8.onHoverState.IconRightImage = null;
            this.bunifuButton8.OnIdleState.BorderColor = System.Drawing.Color.Maroon;
            this.bunifuButton8.OnIdleState.BorderRadius = 40;
            this.bunifuButton8.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton8.OnIdleState.BorderThickness = 2;
            this.bunifuButton8.OnIdleState.FillColor = System.Drawing.Color.GhostWhite;
            this.bunifuButton8.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton8.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton8.OnIdleState.IconLeftImage")));
            this.bunifuButton8.OnIdleState.IconRightImage = null;
            this.bunifuButton8.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton8.OnPressedState.BorderRadius = 40;
            this.bunifuButton8.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton8.OnPressedState.BorderThickness = 2;
            this.bunifuButton8.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton8.OnPressedState.ForeColor = System.Drawing.Color.Maroon;
            this.bunifuButton8.OnPressedState.IconLeftImage = null;
            this.bunifuButton8.OnPressedState.IconRightImage = null;
            this.bunifuButton8.Size = new System.Drawing.Size(610, 61);
            this.bunifuButton8.TabIndex = 33;
            this.bunifuButton8.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton8.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton8.TextMarginLeft = 0;
            this.bunifuButton8.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton8.UseDefaultRadiusAndThickness = true;
            this.bunifuButton8.Click += new System.EventHandler(this.bunifuButton8_Click);
            // 
            // bunifuButton9
            // 
            this.bunifuButton9.AllowAnimations = true;
            this.bunifuButton9.AllowMouseEffects = true;
            this.bunifuButton9.AllowToggling = true;
            this.bunifuButton9.AnimationSpeed = 200;
            this.bunifuButton9.AutoGenerateColors = false;
            this.bunifuButton9.AutoRoundBorders = false;
            this.bunifuButton9.AutoSizeLeftIcon = true;
            this.bunifuButton9.AutoSizeRightIcon = true;
            this.bunifuButton9.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton9.BackColor1 = System.Drawing.Color.GhostWhite;
            this.bunifuButton9.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton9.BackgroundImage")));
            this.bunifuButton9.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.bunifuButton9.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton9.ButtonText = "آشنایی با پوزیشن های بیمار، دندانپزشک و دستیار";
            this.bunifuButton9.ButtonTextMarginLeft = 0;
            this.bunifuButton9.CausesValidation = false;
            this.bunifuButton9.ColorContrastOnClick = 500;
            this.bunifuButton9.ColorContrastOnHover = 0;
            this.bunifuButton9.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.bunifuButton9.CustomizableEdges = borderEdges10;
            this.bunifuButton9.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton9.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton9.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton9.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton9.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.bunifuButton9.Font = new System.Drawing.Font("2  Baran", 20F);
            this.bunifuButton9.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton9.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton9.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton9.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton9.IconMarginLeft = 11;
            this.bunifuButton9.IconPadding = 10;
            this.bunifuButton9.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton9.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton9.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton9.IconSize = 25;
            this.bunifuButton9.IdleBorderColor = System.Drawing.Color.Maroon;
            this.bunifuButton9.IdleBorderRadius = 40;
            this.bunifuButton9.IdleBorderThickness = 2;
            this.bunifuButton9.IdleFillColor = System.Drawing.Color.GhostWhite;
            this.bunifuButton9.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton9.IdleIconLeftImage")));
            this.bunifuButton9.IdleIconRightImage = null;
            this.bunifuButton9.ImeMode = System.Windows.Forms.ImeMode.AlphaFull;
            this.bunifuButton9.IndicateFocus = true;
            this.bunifuButton9.Location = new System.Drawing.Point(188, 112);
            this.bunifuButton9.Name = "bunifuButton9";
            this.bunifuButton9.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton9.OnDisabledState.BorderRadius = 40;
            this.bunifuButton9.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton9.OnDisabledState.BorderThickness = 2;
            this.bunifuButton9.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuButton9.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton9.OnDisabledState.IconLeftImage = null;
            this.bunifuButton9.OnDisabledState.IconRightImage = null;
            this.bunifuButton9.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton9.onHoverState.BorderRadius = 40;
            this.bunifuButton9.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton9.onHoverState.BorderThickness = 2;
            this.bunifuButton9.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton9.onHoverState.ForeColor = System.Drawing.Color.Maroon;
            this.bunifuButton9.onHoverState.IconLeftImage = null;
            this.bunifuButton9.onHoverState.IconRightImage = null;
            this.bunifuButton9.OnIdleState.BorderColor = System.Drawing.Color.Maroon;
            this.bunifuButton9.OnIdleState.BorderRadius = 40;
            this.bunifuButton9.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton9.OnIdleState.BorderThickness = 2;
            this.bunifuButton9.OnIdleState.FillColor = System.Drawing.Color.GhostWhite;
            this.bunifuButton9.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton9.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton9.OnIdleState.IconLeftImage")));
            this.bunifuButton9.OnIdleState.IconRightImage = null;
            this.bunifuButton9.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton9.OnPressedState.BorderRadius = 40;
            this.bunifuButton9.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton9.OnPressedState.BorderThickness = 2;
            this.bunifuButton9.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton9.OnPressedState.ForeColor = System.Drawing.Color.Maroon;
            this.bunifuButton9.OnPressedState.IconLeftImage = null;
            this.bunifuButton9.OnPressedState.IconRightImage = null;
            this.bunifuButton9.Size = new System.Drawing.Size(610, 61);
            this.bunifuButton9.TabIndex = 34;
            this.bunifuButton9.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton9.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton9.TextMarginLeft = 0;
            this.bunifuButton9.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton9.UseDefaultRadiusAndThickness = true;
            this.bunifuButton9.Click += new System.EventHandler(this.bunifuButton9_Click);
            // 
            // pictureBox2
            // 
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(27, 60);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(126, 155);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 6;
            this.pictureBox2.TabStop = false;
            this.pictureBox2.Click += new System.EventHandler(this.pictureBox2_Click);
            // 
            // pictureBox3
            // 
            this.pictureBox3.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox3.Image")));
            this.pictureBox3.Location = new System.Drawing.Point(27, 221);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new System.Drawing.Size(126, 122);
            this.pictureBox3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox3.TabIndex = 7;
            this.pictureBox3.TabStop = false;
            this.pictureBox3.Click += new System.EventHandler(this.pictureBox3_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(27, 12);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(126, 42);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.TabStop = false;
            this.pictureBox1.Click += new System.EventHandler(this.pictureBox1_Click);
            // 
            // MohtavaAmozeshiForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(986, 690);
            this.Controls.Add(this.bunifuButton9);
            this.Controls.Add(this.bunifuButton8);
            this.Controls.Add(this.bunifuButton7);
            this.Controls.Add(this.bunifuButton3);
            this.Controls.Add(this.bunifuButton2);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.Mohtava);
            this.Controls.Add(this.panel1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "MohtavaAmozeshiForm";
            this.Text = "محتوای آموزشی";
            this.panel2.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel2;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Mohtava;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton NarmNiyaz;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton About;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton MoarefiKetab;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton MorefiNarmAfzar;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton7;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton8;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton9;
        private System.Windows.Forms.PictureBox pictureBox3;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.PictureBox pictureBox1;
    }
}