
namespace WindowsFormsApp4
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel2 = new System.Windows.Forms.Panel();
            this.bunifuImageButton2 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.Korikolom = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.marja = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Poster = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Mohtava = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.NarmNiyaz = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.About = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.MorefiNarmAfzar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox3 = new System.Windows.Forms.PictureBox();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            this.SuspendLayout();
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.DarkRed;
            this.panel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.panel2.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.panel2.Controls.Add(this.bunifuImageButton2);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Right;
            this.panel2.Location = new System.Drawing.Point(815, 0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(171, 674);
            this.panel2.TabIndex = 21;
            this.panel2.Paint += new System.Windows.Forms.PaintEventHandler(this.panel2_Paint);
            // 
            // bunifuImageButton2
            // 
            this.bunifuImageButton2.ActiveImage = null;
            this.bunifuImageButton2.AllowAnimations = true;
            this.bunifuImageButton2.AllowBuffering = false;
            this.bunifuImageButton2.AllowToggling = false;
            this.bunifuImageButton2.AllowZooming = true;
            this.bunifuImageButton2.AllowZoomingOnFocus = false;
            this.bunifuImageButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton2.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.ErrorImage")));
            this.bunifuImageButton2.FadeWhenInactive = false;
            this.bunifuImageButton2.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.Image")));
            this.bunifuImageButton2.ImageActive = null;
            this.bunifuImageButton2.ImageLocation = null;
            this.bunifuImageButton2.ImageMargin = 0;
            this.bunifuImageButton2.ImageSize = new System.Drawing.Size(165, 543);
            this.bunifuImageButton2.ImageZoomSize = new System.Drawing.Size(166, 544);
            this.bunifuImageButton2.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.InitialImage")));
            this.bunifuImageButton2.Location = new System.Drawing.Point(3, 43);
            this.bunifuImageButton2.Margin = new System.Windows.Forms.Padding(3, 5, 3, 5);
            this.bunifuImageButton2.Name = "bunifuImageButton2";
            this.bunifuImageButton2.Rotation = 0;
            this.bunifuImageButton2.ShowActiveImage = true;
            this.bunifuImageButton2.ShowCursorChanges = true;
            this.bunifuImageButton2.ShowImageBorders = true;
            this.bunifuImageButton2.ShowSizeMarkers = false;
            this.bunifuImageButton2.Size = new System.Drawing.Size(166, 544);
            this.bunifuImageButton2.TabIndex = 0;
            this.bunifuImageButton2.ToolTipText = "";
            this.bunifuImageButton2.WaitOnLoad = false;
            this.bunifuImageButton2.Zoom = 0;
            this.bunifuImageButton2.ZoomSpeed = 10;
            this.bunifuImageButton2.Click += new System.EventHandler(this.bunifuImageButton2_Click);
            // 
            // Korikolom
            // 
            this.Korikolom.AllowAnimations = true;
            this.Korikolom.AllowMouseEffects = true;
            this.Korikolom.AllowToggling = true;
            this.Korikolom.AnimationSpeed = 200;
            this.Korikolom.AutoGenerateColors = false;
            this.Korikolom.AutoRoundBorders = false;
            this.Korikolom.AutoSizeLeftIcon = true;
            this.Korikolom.AutoSizeRightIcon = true;
            this.Korikolom.BackColor = System.Drawing.Color.Transparent;
            this.Korikolom.BackColor1 = System.Drawing.Color.GhostWhite;
            this.Korikolom.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Korikolom.BackgroundImage")));
            this.Korikolom.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.Korikolom.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Korikolom.ButtonText = "کوریکولوم آموزشی";
            this.Korikolom.ButtonTextMarginLeft = 0;
            this.Korikolom.CausesValidation = false;
            this.Korikolom.ColorContrastOnClick = 500;
            this.Korikolom.ColorContrastOnHover = 0;
            this.Korikolom.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.Korikolom.CustomizableEdges = borderEdges1;
            this.Korikolom.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Korikolom.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Korikolom.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Korikolom.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.Korikolom.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.Korikolom.Font = new System.Drawing.Font("2  Baran", 20F);
            this.Korikolom.ForeColor = System.Drawing.Color.Black;
            this.Korikolom.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Korikolom.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Korikolom.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Korikolom.IconMarginLeft = 11;
            this.Korikolom.IconPadding = 10;
            this.Korikolom.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Korikolom.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Korikolom.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Korikolom.IconSize = 25;
            this.Korikolom.IdleBorderColor = System.Drawing.Color.Maroon;
            this.Korikolom.IdleBorderRadius = 80;
            this.Korikolom.IdleBorderThickness = 2;
            this.Korikolom.IdleFillColor = System.Drawing.Color.GhostWhite;
            this.Korikolom.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("Korikolom.IdleIconLeftImage")));
            this.Korikolom.IdleIconRightImage = null;
            this.Korikolom.ImeMode = System.Windows.Forms.ImeMode.AlphaFull;
            this.Korikolom.IndicateFocus = true;
            this.Korikolom.Location = new System.Drawing.Point(516, 458);
            this.Korikolom.Name = "Korikolom";
            this.Korikolom.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Korikolom.OnDisabledState.BorderRadius = 80;
            this.Korikolom.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Korikolom.OnDisabledState.BorderThickness = 2;
            this.Korikolom.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Korikolom.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.Korikolom.OnDisabledState.IconLeftImage = null;
            this.Korikolom.OnDisabledState.IconRightImage = null;
            this.Korikolom.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Korikolom.onHoverState.BorderRadius = 80;
            this.Korikolom.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Korikolom.onHoverState.BorderThickness = 2;
            this.Korikolom.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Korikolom.onHoverState.ForeColor = System.Drawing.Color.Maroon;
            this.Korikolom.onHoverState.IconLeftImage = null;
            this.Korikolom.onHoverState.IconRightImage = null;
            this.Korikolom.OnIdleState.BorderColor = System.Drawing.Color.Maroon;
            this.Korikolom.OnIdleState.BorderRadius = 80;
            this.Korikolom.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Korikolom.OnIdleState.BorderThickness = 2;
            this.Korikolom.OnIdleState.FillColor = System.Drawing.Color.GhostWhite;
            this.Korikolom.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Korikolom.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("Korikolom.OnIdleState.IconLeftImage")));
            this.Korikolom.OnIdleState.IconRightImage = null;
            this.Korikolom.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Korikolom.OnPressedState.BorderRadius = 80;
            this.Korikolom.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Korikolom.OnPressedState.BorderThickness = 2;
            this.Korikolom.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Korikolom.OnPressedState.ForeColor = System.Drawing.Color.Maroon;
            this.Korikolom.OnPressedState.IconLeftImage = null;
            this.Korikolom.OnPressedState.IconRightImage = null;
            this.Korikolom.Size = new System.Drawing.Size(280, 115);
            this.Korikolom.TabIndex = 25;
            this.Korikolom.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Korikolom.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Korikolom.TextMarginLeft = 0;
            this.Korikolom.TextPadding = new System.Windows.Forms.Padding(0);
            this.Korikolom.UseDefaultRadiusAndThickness = true;
            this.Korikolom.Click += new System.EventHandler(this.Korikolom_Click);
            // 
            // marja
            // 
            this.marja.AllowAnimations = true;
            this.marja.AllowMouseEffects = true;
            this.marja.AllowToggling = true;
            this.marja.AnimationSpeed = 200;
            this.marja.AutoGenerateColors = false;
            this.marja.AutoRoundBorders = false;
            this.marja.AutoSizeLeftIcon = true;
            this.marja.AutoSizeRightIcon = true;
            this.marja.BackColor = System.Drawing.Color.Transparent;
            this.marja.BackColor1 = System.Drawing.Color.GhostWhite;
            this.marja.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("marja.BackgroundImage")));
            this.marja.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.marja.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.marja.ButtonText = "کتب مرجع";
            this.marja.ButtonTextMarginLeft = 0;
            this.marja.CausesValidation = false;
            this.marja.ColorContrastOnClick = 500;
            this.marja.ColorContrastOnHover = 0;
            this.marja.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.marja.CustomizableEdges = borderEdges2;
            this.marja.DialogResult = System.Windows.Forms.DialogResult.None;
            this.marja.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.marja.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.marja.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.marja.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.marja.Font = new System.Drawing.Font("2  Baran", 20F);
            this.marja.ForeColor = System.Drawing.Color.Black;
            this.marja.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.marja.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.marja.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.marja.IconMarginLeft = 11;
            this.marja.IconPadding = 10;
            this.marja.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.marja.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.marja.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.marja.IconSize = 25;
            this.marja.IdleBorderColor = System.Drawing.Color.Maroon;
            this.marja.IdleBorderRadius = 80;
            this.marja.IdleBorderThickness = 2;
            this.marja.IdleFillColor = System.Drawing.Color.GhostWhite;
            this.marja.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("marja.IdleIconLeftImage")));
            this.marja.IdleIconRightImage = null;
            this.marja.ImeMode = System.Windows.Forms.ImeMode.AlphaFull;
            this.marja.IndicateFocus = true;
            this.marja.Location = new System.Drawing.Point(516, 302);
            this.marja.Name = "marja";
            this.marja.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.marja.OnDisabledState.BorderRadius = 80;
            this.marja.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.marja.OnDisabledState.BorderThickness = 2;
            this.marja.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.marja.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.marja.OnDisabledState.IconLeftImage = null;
            this.marja.OnDisabledState.IconRightImage = null;
            this.marja.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.marja.onHoverState.BorderRadius = 80;
            this.marja.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.marja.onHoverState.BorderThickness = 2;
            this.marja.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.marja.onHoverState.ForeColor = System.Drawing.Color.Maroon;
            this.marja.onHoverState.IconLeftImage = null;
            this.marja.onHoverState.IconRightImage = null;
            this.marja.OnIdleState.BorderColor = System.Drawing.Color.Maroon;
            this.marja.OnIdleState.BorderRadius = 80;
            this.marja.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.marja.OnIdleState.BorderThickness = 2;
            this.marja.OnIdleState.FillColor = System.Drawing.Color.GhostWhite;
            this.marja.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.marja.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("marja.OnIdleState.IconLeftImage")));
            this.marja.OnIdleState.IconRightImage = null;
            this.marja.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.marja.OnPressedState.BorderRadius = 80;
            this.marja.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.marja.OnPressedState.BorderThickness = 2;
            this.marja.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.marja.OnPressedState.ForeColor = System.Drawing.Color.Maroon;
            this.marja.OnPressedState.IconLeftImage = null;
            this.marja.OnPressedState.IconRightImage = null;
            this.marja.Size = new System.Drawing.Size(280, 131);
            this.marja.TabIndex = 24;
            this.marja.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.marja.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.marja.TextMarginLeft = 0;
            this.marja.TextPadding = new System.Windows.Forms.Padding(0);
            this.marja.UseDefaultRadiusAndThickness = true;
            this.marja.Click += new System.EventHandler(this.marja_Click);
            // 
            // Poster
            // 
            this.Poster.AllowAnimations = true;
            this.Poster.AllowMouseEffects = true;
            this.Poster.AllowToggling = true;
            this.Poster.AnimationSpeed = 200;
            this.Poster.AutoGenerateColors = false;
            this.Poster.AutoRoundBorders = false;
            this.Poster.AutoSizeLeftIcon = true;
            this.Poster.AutoSizeRightIcon = true;
            this.Poster.BackColor = System.Drawing.Color.Transparent;
            this.Poster.BackColor1 = System.Drawing.Color.GhostWhite;
            this.Poster.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Poster.BackgroundImage")));
            this.Poster.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.Poster.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Poster.ButtonText = "پوستر آموزشی";
            this.Poster.ButtonTextMarginLeft = 0;
            this.Poster.CausesValidation = false;
            this.Poster.ColorContrastOnClick = 500;
            this.Poster.ColorContrastOnHover = 0;
            this.Poster.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.Poster.CustomizableEdges = borderEdges3;
            this.Poster.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Poster.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Poster.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Poster.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.Poster.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.Poster.Font = new System.Drawing.Font("2  Baran", 20F);
            this.Poster.ForeColor = System.Drawing.Color.Black;
            this.Poster.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Poster.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Poster.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Poster.IconMarginLeft = 11;
            this.Poster.IconPadding = 10;
            this.Poster.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Poster.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Poster.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Poster.IconSize = 25;
            this.Poster.IdleBorderColor = System.Drawing.Color.Maroon;
            this.Poster.IdleBorderRadius = 80;
            this.Poster.IdleBorderThickness = 2;
            this.Poster.IdleFillColor = System.Drawing.Color.GhostWhite;
            this.Poster.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("Poster.IdleIconLeftImage")));
            this.Poster.IdleIconRightImage = null;
            this.Poster.ImeMode = System.Windows.Forms.ImeMode.AlphaFull;
            this.Poster.IndicateFocus = true;
            this.Poster.Location = new System.Drawing.Point(516, 163);
            this.Poster.Name = "Poster";
            this.Poster.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Poster.OnDisabledState.BorderRadius = 80;
            this.Poster.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Poster.OnDisabledState.BorderThickness = 2;
            this.Poster.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Poster.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.Poster.OnDisabledState.IconLeftImage = null;
            this.Poster.OnDisabledState.IconRightImage = null;
            this.Poster.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Poster.onHoverState.BorderRadius = 80;
            this.Poster.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Poster.onHoverState.BorderThickness = 2;
            this.Poster.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Poster.onHoverState.ForeColor = System.Drawing.Color.Maroon;
            this.Poster.onHoverState.IconLeftImage = null;
            this.Poster.onHoverState.IconRightImage = null;
            this.Poster.OnIdleState.BorderColor = System.Drawing.Color.Maroon;
            this.Poster.OnIdleState.BorderRadius = 80;
            this.Poster.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Poster.OnIdleState.BorderThickness = 2;
            this.Poster.OnIdleState.FillColor = System.Drawing.Color.GhostWhite;
            this.Poster.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Poster.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("Poster.OnIdleState.IconLeftImage")));
            this.Poster.OnIdleState.IconRightImage = null;
            this.Poster.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Poster.OnPressedState.BorderRadius = 80;
            this.Poster.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Poster.OnPressedState.BorderThickness = 2;
            this.Poster.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Poster.OnPressedState.ForeColor = System.Drawing.Color.Maroon;
            this.Poster.OnPressedState.IconLeftImage = null;
            this.Poster.OnPressedState.IconRightImage = null;
            this.Poster.Size = new System.Drawing.Size(280, 126);
            this.Poster.TabIndex = 23;
            this.Poster.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Poster.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Poster.TextMarginLeft = 0;
            this.Poster.TextPadding = new System.Windows.Forms.Padding(0);
            this.Poster.UseDefaultRadiusAndThickness = true;
            this.Poster.Click += new System.EventHandler(this.Poster_Click);
            // 
            // Mohtava
            // 
            this.Mohtava.AllowAnimations = true;
            this.Mohtava.AllowMouseEffects = true;
            this.Mohtava.AllowToggling = true;
            this.Mohtava.AnimationSpeed = 200;
            this.Mohtava.AutoGenerateColors = false;
            this.Mohtava.AutoRoundBorders = false;
            this.Mohtava.AutoSizeLeftIcon = true;
            this.Mohtava.AutoSizeRightIcon = true;
            this.Mohtava.BackColor = System.Drawing.Color.Transparent;
            this.Mohtava.BackColor1 = System.Drawing.Color.GhostWhite;
            this.Mohtava.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Mohtava.BackgroundImage")));
            this.Mohtava.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.Mohtava.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Mohtava.ButtonText = "محتوای آموزشی";
            this.Mohtava.ButtonTextMarginLeft = 0;
            this.Mohtava.CausesValidation = false;
            this.Mohtava.ColorContrastOnClick = 500;
            this.Mohtava.ColorContrastOnHover = 0;
            this.Mohtava.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.Mohtava.CustomizableEdges = borderEdges4;
            this.Mohtava.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Mohtava.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Mohtava.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Mohtava.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.Mohtava.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.Mohtava.Font = new System.Drawing.Font("2  Baran", 20F);
            this.Mohtava.ForeColor = System.Drawing.Color.Black;
            this.Mohtava.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Mohtava.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Mohtava.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Mohtava.IconMarginLeft = 11;
            this.Mohtava.IconPadding = 10;
            this.Mohtava.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Mohtava.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Mohtava.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Mohtava.IconSize = 25;
            this.Mohtava.IdleBorderColor = System.Drawing.Color.Maroon;
            this.Mohtava.IdleBorderRadius = 80;
            this.Mohtava.IdleBorderThickness = 2;
            this.Mohtava.IdleFillColor = System.Drawing.Color.GhostWhite;
            this.Mohtava.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("Mohtava.IdleIconLeftImage")));
            this.Mohtava.IdleIconRightImage = null;
            this.Mohtava.ImeMode = System.Windows.Forms.ImeMode.AlphaFull;
            this.Mohtava.IndicateFocus = true;
            this.Mohtava.Location = new System.Drawing.Point(516, 31);
            this.Mohtava.Name = "Mohtava";
            this.Mohtava.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Mohtava.OnDisabledState.BorderRadius = 80;
            this.Mohtava.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Mohtava.OnDisabledState.BorderThickness = 2;
            this.Mohtava.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Mohtava.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.Mohtava.OnDisabledState.IconLeftImage = null;
            this.Mohtava.OnDisabledState.IconRightImage = null;
            this.Mohtava.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Mohtava.onHoverState.BorderRadius = 80;
            this.Mohtava.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Mohtava.onHoverState.BorderThickness = 2;
            this.Mohtava.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Mohtava.onHoverState.ForeColor = System.Drawing.Color.Maroon;
            this.Mohtava.onHoverState.IconLeftImage = null;
            this.Mohtava.onHoverState.IconRightImage = null;
            this.Mohtava.OnIdleState.BorderColor = System.Drawing.Color.Maroon;
            this.Mohtava.OnIdleState.BorderRadius = 80;
            this.Mohtava.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Mohtava.OnIdleState.BorderThickness = 2;
            this.Mohtava.OnIdleState.FillColor = System.Drawing.Color.GhostWhite;
            this.Mohtava.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Mohtava.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("Mohtava.OnIdleState.IconLeftImage")));
            this.Mohtava.OnIdleState.IconRightImage = null;
            this.Mohtava.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Mohtava.OnPressedState.BorderRadius = 80;
            this.Mohtava.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Mohtava.OnPressedState.BorderThickness = 2;
            this.Mohtava.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Mohtava.OnPressedState.ForeColor = System.Drawing.Color.Maroon;
            this.Mohtava.OnPressedState.IconLeftImage = null;
            this.Mohtava.OnPressedState.IconRightImage = null;
            this.Mohtava.Size = new System.Drawing.Size(280, 117);
            this.Mohtava.TabIndex = 22;
            this.Mohtava.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Mohtava.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Mohtava.TextMarginLeft = 0;
            this.Mohtava.TextPadding = new System.Windows.Forms.Padding(0);
            this.Mohtava.UseDefaultRadiusAndThickness = true;
            this.Mohtava.Click += new System.EventHandler(this.Mohtava_Click);
            // 
            // NarmNiyaz
            // 
            this.NarmNiyaz.AllowAnimations = true;
            this.NarmNiyaz.AllowMouseEffects = true;
            this.NarmNiyaz.AllowToggling = false;
            this.NarmNiyaz.AnimationSpeed = 200;
            this.NarmNiyaz.AutoGenerateColors = false;
            this.NarmNiyaz.AutoRoundBorders = false;
            this.NarmNiyaz.AutoSizeLeftIcon = true;
            this.NarmNiyaz.AutoSizeRightIcon = true;
            this.NarmNiyaz.BackColor = System.Drawing.Color.Transparent;
            this.NarmNiyaz.BackColor1 = System.Drawing.Color.LavenderBlush;
            this.NarmNiyaz.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NarmNiyaz.BackgroundImage")));
            this.NarmNiyaz.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NarmNiyaz.ButtonText = "نرم افزارهای مورد نیاز";
            this.NarmNiyaz.ButtonTextMarginLeft = 0;
            this.NarmNiyaz.ColorContrastOnClick = 45;
            this.NarmNiyaz.ColorContrastOnHover = 45;
            this.NarmNiyaz.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.NarmNiyaz.CustomizableEdges = borderEdges5;
            this.NarmNiyaz.DialogResult = System.Windows.Forms.DialogResult.None;
            this.NarmNiyaz.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.NarmNiyaz.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NarmNiyaz.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.NarmNiyaz.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.NarmNiyaz.Font = new System.Drawing.Font("2  Baran", 10F);
            this.NarmNiyaz.ForeColor = System.Drawing.Color.Black;
            this.NarmNiyaz.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.NarmNiyaz.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.NarmNiyaz.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.NarmNiyaz.IconMarginLeft = 11;
            this.NarmNiyaz.IconPadding = 10;
            this.NarmNiyaz.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.NarmNiyaz.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.NarmNiyaz.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.NarmNiyaz.IconSize = 25;
            this.NarmNiyaz.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(13)))), ((int)(((byte)(49)))));
            this.NarmNiyaz.IdleBorderRadius = 40;
            this.NarmNiyaz.IdleBorderThickness = 1;
            this.NarmNiyaz.IdleFillColor = System.Drawing.Color.LavenderBlush;
            this.NarmNiyaz.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("NarmNiyaz.IdleIconLeftImage")));
            this.NarmNiyaz.IdleIconRightImage = null;
            this.NarmNiyaz.IndicateFocus = false;
            this.NarmNiyaz.Location = new System.Drawing.Point(3, 586);
            this.NarmNiyaz.Name = "NarmNiyaz";
            this.NarmNiyaz.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.NarmNiyaz.OnDisabledState.BorderRadius = 40;
            this.NarmNiyaz.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NarmNiyaz.OnDisabledState.BorderThickness = 1;
            this.NarmNiyaz.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NarmNiyaz.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.NarmNiyaz.OnDisabledState.IconLeftImage = null;
            this.NarmNiyaz.OnDisabledState.IconRightImage = null;
            this.NarmNiyaz.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NarmNiyaz.onHoverState.BorderRadius = 40;
            this.NarmNiyaz.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NarmNiyaz.onHoverState.BorderThickness = 1;
            this.NarmNiyaz.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NarmNiyaz.onHoverState.ForeColor = System.Drawing.Color.White;
            this.NarmNiyaz.onHoverState.IconLeftImage = null;
            this.NarmNiyaz.onHoverState.IconRightImage = null;
            this.NarmNiyaz.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(13)))), ((int)(((byte)(49)))));
            this.NarmNiyaz.OnIdleState.BorderRadius = 40;
            this.NarmNiyaz.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NarmNiyaz.OnIdleState.BorderThickness = 1;
            this.NarmNiyaz.OnIdleState.FillColor = System.Drawing.Color.LavenderBlush;
            this.NarmNiyaz.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.NarmNiyaz.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("NarmNiyaz.OnIdleState.IconLeftImage")));
            this.NarmNiyaz.OnIdleState.IconRightImage = null;
            this.NarmNiyaz.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.NarmNiyaz.OnPressedState.BorderRadius = 40;
            this.NarmNiyaz.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.NarmNiyaz.OnPressedState.BorderThickness = 1;
            this.NarmNiyaz.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.NarmNiyaz.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.NarmNiyaz.OnPressedState.IconLeftImage = null;
            this.NarmNiyaz.OnPressedState.IconRightImage = null;
            this.NarmNiyaz.Size = new System.Drawing.Size(170, 75);
            this.NarmNiyaz.TabIndex = 5;
            this.NarmNiyaz.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.NarmNiyaz.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.NarmNiyaz.TextMarginLeft = 0;
            this.NarmNiyaz.TextPadding = new System.Windows.Forms.Padding(0);
            this.NarmNiyaz.UseDefaultRadiusAndThickness = true;
            this.NarmNiyaz.Click += new System.EventHandler(this.NarmNiyaz_Click);
            // 
            // About
            // 
            this.About.AllowAnimations = true;
            this.About.AllowMouseEffects = true;
            this.About.AllowToggling = false;
            this.About.AnimationSpeed = 200;
            this.About.AutoGenerateColors = false;
            this.About.AutoRoundBorders = false;
            this.About.AutoSizeLeftIcon = true;
            this.About.AutoSizeRightIcon = true;
            this.About.BackColor = System.Drawing.Color.Transparent;
            this.About.BackColor1 = System.Drawing.Color.LavenderBlush;
            this.About.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("About.BackgroundImage")));
            this.About.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.About.ButtonText = "درباره پدیدآورندگان";
            this.About.ButtonTextMarginLeft = 0;
            this.About.ColorContrastOnClick = 45;
            this.About.ColorContrastOnHover = 45;
            this.About.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.About.CustomizableEdges = borderEdges6;
            this.About.DialogResult = System.Windows.Forms.DialogResult.None;
            this.About.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.About.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.About.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.About.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.About.Font = new System.Drawing.Font("2  Baran", 10F);
            this.About.ForeColor = System.Drawing.Color.Black;
            this.About.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.About.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.About.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.About.IconMarginLeft = 11;
            this.About.IconPadding = 10;
            this.About.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.About.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.About.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.About.IconSize = 25;
            this.About.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(13)))), ((int)(((byte)(49)))));
            this.About.IdleBorderRadius = 40;
            this.About.IdleBorderThickness = 1;
            this.About.IdleFillColor = System.Drawing.Color.LavenderBlush;
            this.About.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("About.IdleIconLeftImage")));
            this.About.IdleIconRightImage = null;
            this.About.IndicateFocus = false;
            this.About.Location = new System.Drawing.Point(3, 507);
            this.About.Name = "About";
            this.About.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.About.OnDisabledState.BorderRadius = 40;
            this.About.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.About.OnDisabledState.BorderThickness = 1;
            this.About.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.About.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.About.OnDisabledState.IconLeftImage = null;
            this.About.OnDisabledState.IconRightImage = null;
            this.About.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.About.onHoverState.BorderRadius = 40;
            this.About.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.About.onHoverState.BorderThickness = 1;
            this.About.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.About.onHoverState.ForeColor = System.Drawing.Color.White;
            this.About.onHoverState.IconLeftImage = null;
            this.About.onHoverState.IconRightImage = null;
            this.About.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(13)))), ((int)(((byte)(49)))));
            this.About.OnIdleState.BorderRadius = 40;
            this.About.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.About.OnIdleState.BorderThickness = 1;
            this.About.OnIdleState.FillColor = System.Drawing.Color.LavenderBlush;
            this.About.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.About.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("About.OnIdleState.IconLeftImage")));
            this.About.OnIdleState.IconRightImage = null;
            this.About.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.About.OnPressedState.BorderRadius = 40;
            this.About.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.About.OnPressedState.BorderThickness = 1;
            this.About.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.About.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.About.OnPressedState.IconLeftImage = null;
            this.About.OnPressedState.IconRightImage = null;
            this.About.Size = new System.Drawing.Size(170, 73);
            this.About.TabIndex = 4;
            this.About.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.About.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.About.TextMarginLeft = 0;
            this.About.TextPadding = new System.Windows.Forms.Padding(0);
            this.About.UseDefaultRadiusAndThickness = true;
            this.About.Click += new System.EventHandler(this.About_Click);
            // 
            // MorefiNarmAfzar
            // 
            this.MorefiNarmAfzar.AllowAnimations = true;
            this.MorefiNarmAfzar.AllowMouseEffects = true;
            this.MorefiNarmAfzar.AllowToggling = false;
            this.MorefiNarmAfzar.AnimationSpeed = 200;
            this.MorefiNarmAfzar.AutoGenerateColors = false;
            this.MorefiNarmAfzar.AutoRoundBorders = false;
            this.MorefiNarmAfzar.AutoSizeLeftIcon = true;
            this.MorefiNarmAfzar.AutoSizeRightIcon = true;
            this.MorefiNarmAfzar.BackColor = System.Drawing.Color.Transparent;
            this.MorefiNarmAfzar.BackColor1 = System.Drawing.Color.LavenderBlush;
            this.MorefiNarmAfzar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("MorefiNarmAfzar.BackgroundImage")));
            this.MorefiNarmAfzar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MorefiNarmAfzar.ButtonText = "معرفی نرم افزار";
            this.MorefiNarmAfzar.ButtonTextMarginLeft = 0;
            this.MorefiNarmAfzar.ColorContrastOnClick = 45;
            this.MorefiNarmAfzar.ColorContrastOnHover = 45;
            this.MorefiNarmAfzar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.MorefiNarmAfzar.CustomizableEdges = borderEdges7;
            this.MorefiNarmAfzar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.MorefiNarmAfzar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.MorefiNarmAfzar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.MorefiNarmAfzar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.MorefiNarmAfzar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.MorefiNarmAfzar.Font = new System.Drawing.Font("2  Baran", 12F);
            this.MorefiNarmAfzar.ForeColor = System.Drawing.Color.Black;
            this.MorefiNarmAfzar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.MorefiNarmAfzar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.MorefiNarmAfzar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.MorefiNarmAfzar.IconMarginLeft = 11;
            this.MorefiNarmAfzar.IconPadding = 10;
            this.MorefiNarmAfzar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.MorefiNarmAfzar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.MorefiNarmAfzar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.MorefiNarmAfzar.IconSize = 25;
            this.MorefiNarmAfzar.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(13)))), ((int)(((byte)(49)))));
            this.MorefiNarmAfzar.IdleBorderRadius = 40;
            this.MorefiNarmAfzar.IdleBorderThickness = 1;
            this.MorefiNarmAfzar.IdleFillColor = System.Drawing.Color.LavenderBlush;
            this.MorefiNarmAfzar.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("MorefiNarmAfzar.IdleIconLeftImage")));
            this.MorefiNarmAfzar.IdleIconRightImage = null;
            this.MorefiNarmAfzar.IndicateFocus = false;
            this.MorefiNarmAfzar.Location = new System.Drawing.Point(3, 349);
            this.MorefiNarmAfzar.Name = "MorefiNarmAfzar";
            this.MorefiNarmAfzar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.MorefiNarmAfzar.OnDisabledState.BorderRadius = 40;
            this.MorefiNarmAfzar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MorefiNarmAfzar.OnDisabledState.BorderThickness = 1;
            this.MorefiNarmAfzar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.MorefiNarmAfzar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.MorefiNarmAfzar.OnDisabledState.IconLeftImage = null;
            this.MorefiNarmAfzar.OnDisabledState.IconRightImage = null;
            this.MorefiNarmAfzar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.MorefiNarmAfzar.onHoverState.BorderRadius = 40;
            this.MorefiNarmAfzar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MorefiNarmAfzar.onHoverState.BorderThickness = 1;
            this.MorefiNarmAfzar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.MorefiNarmAfzar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.MorefiNarmAfzar.onHoverState.IconLeftImage = null;
            this.MorefiNarmAfzar.onHoverState.IconRightImage = null;
            this.MorefiNarmAfzar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(13)))), ((int)(((byte)(49)))));
            this.MorefiNarmAfzar.OnIdleState.BorderRadius = 40;
            this.MorefiNarmAfzar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MorefiNarmAfzar.OnIdleState.BorderThickness = 1;
            this.MorefiNarmAfzar.OnIdleState.FillColor = System.Drawing.Color.LavenderBlush;
            this.MorefiNarmAfzar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.MorefiNarmAfzar.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("MorefiNarmAfzar.OnIdleState.IconLeftImage")));
            this.MorefiNarmAfzar.OnIdleState.IconRightImage = null;
            this.MorefiNarmAfzar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.MorefiNarmAfzar.OnPressedState.BorderRadius = 40;
            this.MorefiNarmAfzar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.MorefiNarmAfzar.OnPressedState.BorderThickness = 1;
            this.MorefiNarmAfzar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.MorefiNarmAfzar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.MorefiNarmAfzar.OnPressedState.IconLeftImage = null;
            this.MorefiNarmAfzar.OnPressedState.IconRightImage = null;
            this.MorefiNarmAfzar.Size = new System.Drawing.Size(170, 73);
            this.MorefiNarmAfzar.TabIndex = 1;
            this.MorefiNarmAfzar.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.MorefiNarmAfzar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.MorefiNarmAfzar.TextMarginLeft = 0;
            this.MorefiNarmAfzar.TextPadding = new System.Windows.Forms.Padding(0);
            this.MorefiNarmAfzar.UseDefaultRadiusAndThickness = true;
            this.MorefiNarmAfzar.Click += new System.EventHandler(this.MorefiNarmAfzar_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(27, 12);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(126, 42);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.TabStop = false;
            this.pictureBox1.Click += new System.EventHandler(this.pictureBox1_Click);
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.Firebrick;
            this.panel1.Controls.Add(this.pictureBox3);
            this.panel1.Controls.Add(this.pictureBox2);
            this.panel1.Controls.Add(this.bunifuButton2);
            this.panel1.Controls.Add(this.NarmNiyaz);
            this.panel1.Controls.Add(this.About);
            this.panel1.Controls.Add(this.MorefiNarmAfzar);
            this.panel1.Controls.Add(this.pictureBox1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(182, 674);
            this.panel1.TabIndex = 20;
            this.panel1.Paint += new System.Windows.Forms.PaintEventHandler(this.panel1_Paint);
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.LavenderBlush;
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "معرفی کتاب";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges8;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("2  Baran", 12F);
            this.bunifuButton2.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(13)))), ((int)(((byte)(49)))));
            this.bunifuButton2.IdleBorderRadius = 40;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.LavenderBlush;
            this.bunifuButton2.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.IdleIconLeftImage")));
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(3, 428);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 40;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 40;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(13)))), ((int)(((byte)(49)))));
            this.bunifuButton2.OnIdleState.BorderRadius = 40;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.LavenderBlush;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton2.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.OnIdleState.IconLeftImage")));
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 40;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(170, 73);
            this.bunifuButton2.TabIndex = 6;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // pictureBox3
            // 
            this.pictureBox3.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox3.Image")));
            this.pictureBox3.Location = new System.Drawing.Point(27, 221);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new System.Drawing.Size(126, 122);
            this.pictureBox3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox3.TabIndex = 9;
            this.pictureBox3.TabStop = false;
            this.pictureBox3.Click += new System.EventHandler(this.pictureBox3_Click);
            // 
            // pictureBox2
            // 
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(27, 60);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(126, 155);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 8;
            this.pictureBox2.TabStop = false;
            this.pictureBox2.Click += new System.EventHandler(this.pictureBox2_Click);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(986, 674);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.Korikolom);
            this.Controls.Add(this.marja);
            this.Controls.Add(this.Poster);
            this.Controls.Add(this.Mohtava);
            this.Controls.Add(this.panel1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Form1";
            this.Text = "RDT";
            this.panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel2;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Korikolom;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton marja;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Poster;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Mohtava;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton NarmNiyaz;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton About;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton MorefiNarmAfzar;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private System.Windows.Forms.PictureBox pictureBox3;
        private System.Windows.Forms.PictureBox pictureBox2;
    }
}

